### ISSUE TITLE
yfinance API 확인

### ISSUE THREAD

**Issue by ohdair** [ohdair/STAGO#2]
하루치의 주식 변동 그래프를 수집할 수 있는 API 확인
해외 주식 : [yfinance](https://pypi.org/project/yfinance/)

1. 하루치 주식 변동 그래프 수집 가능 여부

**Comment by Samuel-Jo** [comment]
## 개별종목의 1년치 3분봉 데이터를 불러서
 1. 가격 데이터를 분석하여 30분 이내에 5%이상 상승하는 패턴을 발견하고
 2. 상승하는 패턴에서 상승하기 전 거래량의 변화 패턴을 발견하고
 3. 이 상승패턴을 모델링하여
 4. 현재 주가의 흐름을 파악하여 주식 상승 시작 패턴을 발견하여 매수 포인트 화살표를 표기하고
 5. 매수 후 0.5% 이상 상승시 최고가 대비 0.3% 하단을 가로 점선으로 표기하고 
 6. 이 표기선을 이탈시 매도하는 전략을 가져감.
 7. 이 표기선은 상승시 계속 업데이트 되어야함.

1차적으로 코드를 만들어 돌려 봤으나 엉망인 수준
앞으로 모델을 만드는 일이 험난해 보임
